### PR TITLE
add concerns to auto load paths

### PR DESCRIPTION
**Pull request by lavanyareddyreddy**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
-no

#### Which User story does this relate to?
- #148429363

#### Brief feature description
- add concerns and helpers to auto load paths

#### Does this PR block/effect other stories?
- no

#### Do any commands needs to be run in order to run the project with this PR?
-no

#### Code coverage percent diff as a result of this PR?
- no

#### JS errors diff as a result of this PR?
- no

### CODE REVIEW

**Comment by ratneshraval** [comment]
I don't think we need this anymore since PR #131 fixes the problem without customized autoloading. 
If everyone agrees then I'll close this PR>

**Comment by lavanyareddyreddy** [comment]
No, I dont agree. #131 does not fix the problem of all the unnecessary `Concern::` floating around in the entire codebase. 

Also, this story's acceptance criteria has nothing detailing any other problems apart from cleaning up the name spaces.

**Comment by ratneshraval** [comment]
So cleaning up namespacing will still work without autoloading.
If this allows us to remove Concerns:: from namespace and still lets us modify code without restarting rails server then I say we go ahead with this. If not, what purpose will it serve?

**Comment by lavanyareddyreddy** [comment]
Modify code without restarting rails server has nothing to do with this PR. 

I don't think autoload is necessary because looks like now `app/*/concern` is included in autoload paths by default so, I will take that out.

**Comment by ratneshraval** [comment]
Checked with @lavanyareddyreddy and we agreed to close this PR. So closing this as PR #131 was able to handle the change without coding for autoload at start.

**Pull request closed without merging**
