### PR TITLE
Code owners

### PR DESCRIPTION
**Pull request by ratneshraval**
#### Which User story does this relate to?
- n/a

#### Brief feature description
- Code owners added. At least 1 code owner approval is required, out of 2 total approvals. 
- Code owners will be automatically requested for review (3 less people to choose). 
- Code owners are `lauherkcambria`, `Nasir2712`, `ratneshraval`
- More about code owners: https://help.github.com/articles/about-codeowners/

### CODE REVIEW

**Comment by nasar-cambria** [comment]
@ratneshraval do we need to let backend developer's know about this change so they don't merge PR on approvals from ppl other the code owners?

**Comment by ratneshraval** [comment]
Yes, I'll send out an email but you will not be able to merge anyways. Github protects from merges unless there is one approval from one of the code owners.

**Comment by ratneshraval** [comment]
@anuroop15 link added in PR about code owners. So you don't have to google it.

**Comment by anuroop15** [comment]
I know about code ownership. I just need to know the use of it in this project.

I have few questions regarding keeping this code ownership.
1. This can reduce the PR discussions in places of discussion, if team members take code reviews approval for granted.
2. The availability of code reviewers. There are stories that might not need code owner approval ex: label stories. 
3. This might increases PR review time/ wait time.

**Comment by ratneshraval** [comment]
@lauherkcambria Adding code owners will resolve the confusion around who needs to approve code before a change gets merged in. It will also provide a quality check. The project has code owners for each project, so far we didn't need it but after Thursday's conversation, it seems like this will help.

1. We have 3 code owners so no dependency on 1 developer. If a 3rd team gets added to CALS, we will add someone from that team to the code owners to increase capacity
2. In an ideal world that would work.
3. Everyone is still invited and should review PR to spread the knowledge
4. Everyone should already feel the responsibility for the quality.  

Hope this helps. This does not prevent from adding other developers to the PR, in fact we should add developers for review as we have been doing.

**Comment by lauherkcambria** [comment]
@ratneshraval I thought that the idea behind Thursday's meeting was that having a single person's review required to approve a PR was not ideal and we could get a lot out of the democratization of code reviews. Wouldn't this implementation be the exact opposite of the goal of that conversation?

**Comment by LeonidMarushevskyi** [comment]
I believe this is a step in right direction and good compromise.

**Comment by anuroop15** [comment]
@ratneshraval I don't see a point of waiting for PR's of one/two point stories. 
Earlier we used to have team discussion on PR's that might effect the code quality and we try to fix it. But with this process, I'm not sure if those kind of healthier discussion happen.

If all team members agreed on this, we can go with this approach. Approving it.

**Comment by ratneshraval** [comment]
@anuroop15 this does not prevent anyone from having any discussions. If there is a concern about quality of a PR, the conversation will happen anyways.

**Comment by ratneshraval** [comment]
I'm merging this. Let's try for couple of sprints and re evaluate.

**Pull request merged**
