### PR TITLE
auto populate to whom

### PR DESCRIPTION
**Pull request by lauherkcambria**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
-N/A

#### Which User story does this relate to?
- https://www.pivotaltracker.com/story/show/148788567

#### Brief feature description
- AUTO UPDATE to whom fields based off of user input in applicant

#### Does this PR block/effect other stories?
-no

#### Do any commands needs to be run in order to run the project with this PR?
- rake tmp:cache:clear; rails assets:precompile.

### CODE REVIEW

**Comment by lauherkcambria** [comment]
we will make a pivotal story to address the posting of the to whom data and get this in now as there are some api contract discrepencies on the API side that we will wait on completion for in order to minimize duplicate work.

**Comment by ratneshraval** [comment]
Looks like you extracted setToWhom but still passing it down as props. You can just import it in minorCardFields and not have to worry about passing as props.

**Comment by lauherkcambria** [comment]
good catch @ratneshraval, i'll push a fix for that. thanks for fixing those tests @lavanyareddyreddy!👍 👏 😄

**Comment by ratneshraval** [comment]
This can use few extra test cases, testing setToWhom function to increase coverage.

**Pull request merged**
