### PR TITLE
name type dropdown fix

### PR DESCRIPTION
**Pull request by Nasir2712**
#### Which User story does this relate to?
-

#### Brief feature description
- Name Type dropdown in Name Card was not working. This PR is a fix for this bug

#### Does this PR block/effect other stories?
-

#### Do any commands needs to be run in order to run the project with this PR?
-

#### Code coverage percent diff as a result of this PR?
-

### CODE REVIEW

**Comment by ratneshraval** [comment]
@Nasir2712 so there should be a new test case catching the bug, right?

**Comment by Nasir2712** [comment]
@ratneshraval so if i remember correctly the test was already failing. I fixed the test case and pushed it i believe in some other PR. There should be a test case for name types in completeNameFields.

**Comment by ratneshraval** [comment]
So in development branch we have this bug and all tests pass, means there is not a specific test that failed for this bug, right?

**Comment by lauherkcambria** [comment]
@Nasir2712 i approved, but lets add the test nesh is speaking of as well 😄 👍

**Comment by Nasir2712** [comment]
@lauherkcambria its already there in development branch

**Pull request merged**
