### PR TITLE
Fix for caret positioning on delete windows 7

### PR DESCRIPTION
**Pull request by nasar-cambria**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/AARA-140

#### Brief feature description
- When deleting a digit in the phone number, the digit should be deleted. The cursor should not jump to the beginning of the phone number. The numbers should not move to the left.

#### Does this PR block/effect other stories?
- NA

#### Do any commands needs to be run in order to run the project with this PR?
- NA

#### Code coverage percent diff as a result of this PR?
- NA

### CODE REVIEW

**Comment by LeonidMarushevskyi** [comment]
jenkins please retest this

**Comment by LeonidMarushevskyi** [comment]
jenkins please retest this

**Comment by nasar-cambria** [comment]
jenkins re-test this please

**Comment by lauherkcambria** [comment]
jenkins, retest this please

**Comment by nasar-cambria** [comment]
jenkins re-test this please

**Pull request merged**
