### PR TITLE
SEAR-545 CALS-Facility search and profile acceptance tests

### PR DESCRIPTION
**Pull request by sunilb0575**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/SEAR-545

#### Brief feature description
- Fix CALS facility search and profile acceptance tests

#### Do any commands needs to be run in order to run the project with this PR?
- rspec spec/acceptance/facilities/

### CODE REVIEW

**Comment by sunilb0575** [comment]
jenkins retest this please

**Comment by Nasir2712** [comment]
jenkins retest this please

**Comment by sunilb0575** [comment]
Jenkins retest this please.

**Comment by sunilb0575** [comment]
jenkins retest this please.

**Pull request merged**
