### PR TITLE
hotfix for relationship to freeform, was missing subindex on value call

### PR DESCRIPTION
**Pull request by lauherkcambria**
#### Which User story does this relate to (link)?
-n/a

#### Brief feature description
 hotfix for relationship to freeform on rfa 01c. This  was missing subindex on value call so it wasn't displaying entered characters. 

#### Does this PR block/effect other stories?
-no

#### Do any commands needs to be run in order to run the project with this PR?
-no

#### Code coverage percent diff as a result of this PR?
-n/a

### CODE REVIEW

**Comment by LeonidMarushevskyi** [comment]
@lauherkcambria Please add JIRA issue code into PR title and link to the issue into PR description

**Comment by lauherkcambria** [comment]
jenkins, retest this please.

**Comment by lauherkcambria** [comment]
@LeonidMarushevskyi - @nasar-cambria found this issue and we were able to find a fix  for it before business or QA discovered it - do you want us to make a jira issue story too?

**Comment by lauherkcambria** [comment]
jenkins, retest this please.

**Comment by LeonidMarushevskyi** [comment]
@lauherkcambria It is ok.

**Comment by lauherkcambria** [comment]
jenkins, retest this please.

**Comment by lauherkcambria** [comment]
jenkins, retest this please.

**Pull request merged**
