### PR TITLE
AARA-511 Troubleshoot CALS acceptance tests in PreInt

### PR DESCRIPTION
**Pull request by nasar-cambria**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/AARA-511

#### Brief feature description
- Troubleshoot CALS acceptance tests in PreInt

NOTE: I have commented out test cases in this file and added comments on the top.
https://osi-cwds.atlassian.net/browse/AARA-515

#### Does this PR block/effect other stories?
- 

#### Do any commands needs to be run in order to run the project with this PR?
- NA

#### Code coverage percent diff as a result of this PR?
- NA

### CODE REVIEW

**Comment by nasar-cambria** [comment]
jenkins re-test this please

**Comment by nasar-cambria** [comment]
jenkins re-test this please

**Comment by anuroop15** [comment]
@nasar-cambria Please link the submit button API bug  to this PR.

**Comment by nasar-cambria** [comment]
@anuroop15 Added in description. Thanks!

**Pull request merged**
