### PR TITLE
SEAR-521 Exception - failed to parse query when searching for facility with "/" in name

### PR DESCRIPTION
**Pull request by Nasir2712**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/SEAR-521

#### Brief feature description
- fix special characters error in elastic search.
https://www.npmjs.com/package/elasticsearch-sanitize escapes all special characters.

#### Does this PR block/effect other stories?
-n/a

#### Do any commands need to be run in order to run the project with this PR?
- yarn install

### CODE REVIEW

**Comment by Nasir2712** [comment]
retest this please

**Comment by Nasir2712** [comment]
retest this please

**Comment by Nasir2712** [comment]
retest this please

**Comment by sunilb0575** [comment]
jenkins, retest this please.

**Comment by Nasir2712** [comment]
Retest this please

**Comment by Nasir2712** [comment]
retest this please

**Comment by ratneshraval** [comment]
Looks like a lot of package updates. You should 
1. restore yarn.lock to what we have in master 
2. add your es package with yarn add

**Comment by ratneshraval** [comment]
retest this please

**Pull request closed without merging**
