### PR TITLE
SEAR-296 Add query params to dora end point

### PR DESCRIPTION
**Pull request by Nasir2712**
#### Which User story does this relate to (link)?
-https://osi-cwds.atlassian.net/secure/RapidBoard.jspa?rapidView=209&projectKey=SEAR&selectedIssue=SEAR-296

#### Brief feature description
-n/a

#### Does this PR block/effect other stories?
-n/a

#### Do any commands needs to be run in order to run the project with this PR?
-n/a

#### Code coverage percent diff as a result of this PR?
-n/a

### CODE REVIEW

**Comment by Nasir2712** [comment]
retest this please

**Comment by sunilb0575** [comment]
retest this please

**Comment by Nasir2712** [comment]
jenkins, retest this please

**Comment by Nasir2712** [comment]
@ratneshraval Back-end was able to reduce the number of shards from 5 to 1, so we don't need this query change anymore. As a result of these changes, I am going to close this PR.

**Comment by Nasir2712** [comment]
retest this please

**Comment by Nasir2712** [comment]
retest this please

**Comment by ratneshraval** [comment]
@Nasir2712  let's not close this. I think changing sharding to 1 seems like temporary solution and it may need more shards when the index grows. 
I recommend that we go through with the change so in future, these issue doesn't resurface.

**Comment by Nasir2712** [comment]
closing this PR because of failing tests, this branch was created from 1.0.1 tag so was creating issue, the changes are now in #572

**Pull request closed without merging**
