### PR TITLE
AARA-237: too many redirects

### PR DESCRIPTION
**Pull request by lauherkcambria**
#### Which User story does this relate to (link)?
-https://osi-cwds.atlassian.net/browse/AARA-237

#### Brief feature description
- second attempt to fix the too many redirects issue that occurs on login by 

#### Does this PR block/effect other stories?
-refactor authenticate with cwds to have both redirect and error log in page 

#### Do any commands needs to be run in order to run the project with this PR?
- add CALS_LOGIN_REDIRECT_URL to .env file

#### Code coverage percent diff as a result of this PR?
-86.99% Statements 
 79.07% Branches
 84.32% Functions 
 87.21% Lines

### CODE REVIEW

**Comment by lauherkcambria** [comment]
jenkins, retest this please.

**Comment by anuroop15** [comment]
@lauherkcambria This is always redirecting to Pre-int dashboard page when I tested it in my local. Can you please take a look.

**Comment by lauherkcambria** [comment]
as discussed, @anuroop15 we need to add the env variable CALS_LOGIN_REDIRECT_URL =  http://localhost:5000 for local developement.

**Comment by anuroop15** [comment]
discussed with @lauherkcambria, changed the CALS_LOGIN_REDIRECT_URL to env specific (localhost:5000 in this case). Everything seems working fine. 👍

**Comment by nasar-cambria** [comment]
@lauherkcambria  - I think we can close this PR. Since this issue is fixed in perry.

**Comment by lauherkcambria** [comment]
@nasar-cambria I think you're right, but before we close it I'd like to verify it's ok with it on the backend as well @DmitriyRudenko @LeonidMarushevskyi

**Comment by lauherkcambria** [comment]
closing as resolved on backend. @DmitriyRudenko @LeonidMarushevskyi @nasar-cambria @ratneshraval

**Pull request closed without merging**
