### PR TITLE
WIP- User logout

### PR DESCRIPTION
**Pull request by Nasir2712**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
-

#### Which User story does this relate to?
- https://www.pivotaltracker.com/n/projects/1662141/stories/151454599

#### Brief feature description
- user logout

#### Does this PR block/effect other stories?
- no

#### Do any commands needs to be run in order to run the project with this PR?
- 

#### Code coverage percent diff as a result of this PR?
-

#### JS errors diff as a result of this PR?
-

### CODE REVIEW

**Comment by Nasir2712** [comment]
jenkins, retest this please

**Comment by Nasir2712** [comment]
jenkins, retest this please

**Comment by Nasir2712** [comment]
jenkins, retest this please

**Comment by Nasir2712** [comment]
@ratneshraval my logout branch got merged in global header. I think this PR could be removed now.

**Comment by ratneshraval** [comment]
@Nasir2712 you'll still need part of this work when you import the latest version of react-wood-duck.

**Pull request closed without merging**
