### PR TITLE
Import dropdown in SearchInput

### PR DESCRIPTION
**Pull request by sunilb0575**
#### Which User story does this relate to?
-No

#### Brief feature description
- Add dropdown component to searchInput.
- Clean up facility profile and search component's names. 

#### Does this PR block/effect other stories?
- No

#### Do any commands needs to be run in order to run the project with this PR?
- No

#### Code coverage percent diff as a result of this PR?
- No

### CODE REVIEW

**Comment by Nasir2712** [comment]
scrollspy didn't work.

**Comment by Nasir2712** [comment]
jenkins, retest this please

**Comment by Nasir2712** [comment]
jenkins, retest this please

**Comment by Nasir2712** [comment]
@ratneshraval  what annoys me is that it passes with every approach!

**Comment by Nasir2712** [comment]
jenkins, retest this please

**Comment by sunilb0575** [comment]
You're Welcome. @ratneshraval

**Pull request merged**
