### PR TITLE
Phone card refactor

### PR DESCRIPTION
**Pull request by ratneshraval**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
- yes

#### Brief feature description
- Phone component refactor 

#### Do any commands needs to be run in order to run the project with this PR?
- yarn install

#### JS errors diff as a result of this PR?
- 78

### CODE REVIEW

**Comment by lauherkcambria** [comment]
jenkins, retest this please.

**Comment by lauherkcambria** [comment]
jenkins, retest this please.

**Comment by ratneshraval** [comment]
Jenkins, retest this please.

**Comment by ratneshraval** [comment]
@anuroop15 I'll update this as part of the applicant save update. Can you still approve and merge this in?

**Comment by anuroop15** [comment]
👍  sure

**Pull request merged**
