### PR TITLE
CALS-5823 Facility tests - update with new facility data

### PR DESCRIPTION
**Pull request by sunilb0575**
#### Which User story does this relate to?
- https://osi-cwds.atlassian.net/browse/CALS-5823

#### Brief feature description
- Update facility search and profile rspec tests with new data.

#### Does this PR block/effect other stories?
- No

#### Do any commands needs to be run in order to run the project with this PR? 
- rspec spec
- yarn spec-end2end-features

#### Code coverage percent diff as a result of this PR?
- No

### CODE REVIEW

**Comment by Nasir2712** [comment]
@ratneshraval @sunilb0575  so I assume we will be having some kind of pipeline for deployment to staging env. So, don't you think if the data is different some of the test cases might fail which might halt deployment?

**Comment by sunilb0575** [comment]
@Nasir2712 yes, I tried writing data independent test cases for few. But some features are difficult to test without exact data. 
It would have been better if all the environments have same data.

**Comment by ratneshraval** [comment]
@Nasir2712 @sunilb0575 Staging may have different set of data but it may also have different set of tests. I think this approach is good till we figure out what is needed in staging.

**Comment by Nasir2712** [comment]
@ratneshraval  I think we should comment out children and the complaint tests or any data dependent tests just because they will fail on staging. Can the test cases be switched based on environment? or is that even a good idea?

**Comment by ratneshraval** [comment]
@Nasir2712 let's comment that out when it fails in staging, not right now. By then we'll figure out testing strategy for staging.

**Pull request merged**
