### PR TITLE
Sp2.5 link profile to search

### PR DESCRIPTION
**Pull request by anuroop15**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
-Javascript tests for profile page links in search page. All tests passed

#### Which User story does this relate to?
- #144050395

#### Brief feature description
- Ability lo load Facility profile page from search results. 

#### Does this PR block/effect other stories?
-No

#### Do any commands needs to be run in order to run the project with this PR?
-npm run dev

#### Code coverage percent diff as a result of this PR?
-JS 90.1%, rspec: 72.21%

#### JS errors diff as a result of this PR?
-21

### CODE REVIEW

**Comment by ratneshraval** [comment]
Let's pair and review this tomorrow.

**Comment by anuroop15** [comment]
@lauherkcambria 
1) Nice thought on rendering mock data as a factory. I initially thought of keeping it separate so that we can use it a singleton object. I will refactor it going further in other US's.
@2: Not user on how the UX design goes. but if there wasn't a back button, we will make search results saved when browser back button was clicked. Which comes in separate User story.

**Comment by lauherkcambria** [comment]
@anuroop15 awesome, thanks for your reply! 👍 

re: @2 what do you mean by 'we will make search results saved when browser back button was clicked'? 

I just thought this will most certainly become a requested feature later on, so it may be a good idea to at least start thinking about it now.

**Comment by anuroop15** [comment]
re:@2  I mean browser default back button. 
correct!! I'm checking the best method to handle back button.

**Pull request merged**
