### PR TITLE
Add rollback for CALS app release pipeline

### PR DESCRIPTION
**Pull request by SergiiRedchuk**
fixing FATAL: [ssh-agent] Could not find specified credentials

https://osi-cwds.atlassian.net/browse/FIT-577

### CODE REVIEW

**Comment by SergiiRedchuk** [comment]
@GajulaNagaPradeep , @Nasir2712 , @sunilb0575 , notable changes you might want to know about are in this PR: https://github.com/ca-cwds/CALS/pull/720

**Comment by SergiiRedchuk** [comment]
retest this please

**Comment by SergiiRedchuk** [comment]
retest this please

**Comment by GajulaNagaPradeep** [comment]
retest this please

**Comment by SergiiRedchuk** [comment]
retest this please

**Pull request merged**
