### PR TITLE
AARA-423 Restrict  CARES feature access as per roles and permissions

### PR DESCRIPTION
**Pull request by nasar-cambria**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/AARA-423

#### Brief feature description
- As a CARES user, Access to features should be restricted based on the roles and privileges so that user do not see or update information that he is permitted to see or update.

#### Does this PR block/effect other stories?
- No

#### Do any commands needs to be run in order to run the project with this PR?
- No

#### Code coverage percent diff as a result of this PR?
- NA

### CODE REVIEW

**Comment by nasar-cambria** [comment]
jenkins re test this please

**Comment by nasar-cambria** [comment]
jenkins re test this please

**Comment by nasar-cambria** [comment]
jenkins re test this please

**Comment by nasar-cambria** [comment]
jenkins re test this please

**Comment by nasar-cambria** [comment]
jenkins re test this please

**Comment by nasar-cambria** [comment]
jenkins re test this please

**Comment by nasar-cambria** [comment]
jenkins retest this please

**Comment by LeonidMarushevskyi** [comment]
jenkins, retest this please.

**Pull request merged**
