### PR TITLE
WIP CALS-5696 Removing (required) label from Employment Card

### PR DESCRIPTION
**Pull request by nasar-cambria**
#### Which User story does this relate to?
- https://osi-cwds.atlassian.net/browse/CALS-5696

#### Brief feature description
- Since the (required) label in address fields are coming from wood-duck its adding (required) label to every common address component in RFA 01A. We need to make sure this label is only added to fields which are required.

#### Does this PR block/effect other stories?
- no

#### Do any commands needs to be run in order to run the project with this PR?
- no

#### Code coverage percent diff as a result of this PR?
- NA

### CODE REVIEW

**Comment by ratneshraval** [comment]
There is a constant declared for ` required` text. shouldn't we be using that?

**Comment by Nasir2712** [comment]
I was never a fan of that approach having react component evaluating the object at rendering time for a string. Unnecessary evaluation.

**Comment by ratneshraval** [comment]
@Nasir2712 That is a good point. We should've corrected/commented when that approach got it.

**Comment by Nasir2712** [comment]
can you remove WIP from the title if this is ready to be reviewed?

**Comment by LeonidMarushevskyi** [comment]
I actually introduced constant for required label. Required label can be consider common business requirement which should be consistent across the application. Having hard coded '(required)' label across different files in application can be considered duplication.  Constant was introduced in attempt to localize this aspect of logic in one place. So if later PO will decide to change required label to * for example, it will be change in one place. I agree that there can be other better ways to have this logic in one place like using of styles but constant was the simplest way.

**Comment by nasar-cambria** [comment]
@Nasir2712  this is not ready to be reviewed yet. I am still waiting on new version to be published from react-wood-duck to be able to see my changes in RFA.

**Comment by nasar-cambria** [comment]
jenkins re-test this please

**Comment by nasar-cambria** [comment]
Created a fresh PR to avoid test failures.

**Pull request closed without merging**
