### PR TITLE
CALS-5550: remove leading spaces in names

### PR DESCRIPTION
**Pull request by DmitriyRudenko**
#### Which User story does this relate to?
https://osi-cwds.atlassian.net/browse/CALS-5550

#### Brief feature 
Per conversation with Leonid, it may still be the case that applicant information is created when NULL applicant exist on the form.

*Acceptance Criteria*
- Null applicant information will not be created until applicant is added to RFA form and saved.
- User is not able to enter blank space as first character of name with no additional alpha-numeric values  behind it.
Example: If user entered ' ' (blank space only) it will be considered no value
If user enters ' 'Leon, application will accept the leading space and save with the name.
DEV NOTE: Determine if in case number two, the leading space to start a name can be parsed out and only save as 'Leon'
- Spaces anywhere else in the name structure are permitted.

#### Does this PR block/effect other stories?
NO

#### Do any commands needs to be run in order to run the project with this PR?
NO

### CODE REVIEW

**Comment by Nasir2712** [comment]
can you add description to PR instead of NO

**Comment by Nasir2712** [comment]
Can you write new feature tests and karma tests for the component that you made changes too?

**Comment by DmitriyRudenko** [comment]
@lauherkcambria 

With your code user will still able to enter leading spaces. Please review the 2nd requirement more carefully.

Also couple of remarks:

1. Multiple trims on the same value is not really efficient
2. first_name or last_name my be undefined, so better to check it
3. Why do we check just first entry here? What is the hidden meaning of "0" index? should it be replaced by constant with more understandable name?
4. I believe you did a typo here: String.length type is integer
5. What function in index.js did you mean? I didn't change any of index.js

Thanks!

**Comment by LeonidMarushevskyi** [comment]
@DmitriyRudenko You need to recird VCR cassette for your test

**Comment by LeonidMarushevskyi** [comment]
PR reworked according to review comments. Feature tests added

**Comment by lauherkcambria** [comment]
image
hmm, something seems a little off when I run this branch from terminal. instead of the save progress button being disabled the add alias button is disabled. See pic

**Comment by ratneshraval** [comment]
@DmitriyRudenko One of @Nasir2712 's request was to add Karma test for the new function to verify functionality. I didn't see that but we have 2 approvals so I"ll merge it. Can you add the karma test for it as well?

**Pull request merged**
