### PR TITLE
CALS-5809 Rspec - 2 deprecation warnings

### PR DESCRIPTION
**Pull request by sunilb0575**
#### Which User story does this relate to?
- https://osi-cwds.atlassian.net/browse/CALS-5809

#### Brief feature description
- Fix deprecation warning when Rspec spec.
-Switch from Rspec 3.5 to Rspec 3.7.
-Gem used to update syntax.
https://github.com/yujinakayama/transpec

#### Does this PR block/effect other stories?
- No

#### Do any commands needs to be run in order to run the project with this PR?
- bundle install

#### Code coverage percent diff as a result of this PR?
- No

### CODE REVIEW

**Comment by Nasir2712** [comment]
update the instructions on how to use the new gem.

**Comment by ratneshraval** [comment]
Do we need to keep the gem if all has been updated? If we need the gem, please move it to `development and test` or `test` group

**Comment by sunilb0575** [comment]
I think we don't need Transpec gem in the future. It just helps in updating syntax, which I already did on whole project. 
Any ways I will keep a link related to gem in the description.

**Comment by Nasir2712** [comment]
I think you should still keep it in the test group so that we could still use it incase if we need it.

**Comment by Nasir2712** [comment]
also, take the screenshots so that you can show in JIRA.

**Pull request merged**
