### PR TITLE
AARA-463 Fix tracking table alignment

### PR DESCRIPTION
**Pull request by nasar-cambria**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/AARA-463

#### Brief feature description
- Column width should be adjusted for checklist items in tracking page

#### Does this PR block/effect other stories?
- NA

#### Do any commands needs to be run in order to run the project with this PR?
- NA

#### Code coverage percent diff as a result of this PR?
- NA

### CODE REVIEW

**Comment by nasar-cambria** [comment]
jenkins, re-test this please.

**Comment by nasar-cambria** [comment]
jenkins re test this please

**Comment by ratneshraval** [comment]
retest this please

**Comment by LeonidMarushevskyi** [comment]
retest this please

**Comment by nasar-cambria** [comment]
re test this please

**Pull request merged**
