### PR TITLE
headless browser testing via phantom and poltergiest. BOO!

### PR DESCRIPTION
**Pull request by lauherkcambria**
scary, BOO~~!

#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
- no tests were added as this  is to upgrade our test suite to use browserless testing instead of chrome so it can be used with CI / jenkins. 

#### Which User story does this relate to?
-  jenkins stories

#### Brief feature description
- switch from chrome to phantomjs for testing

#### Does this PR block/effect other stories?
-

#### Do any commands needs to be run in order to run the project with this PR?
- yarn && bundle update

#### Code coverage percent diff as a result of this PR?
- same 

#### JS errors diff as a result of this PR?
- N/A

### CODE REVIEW

**Comment by ratneshraval** [comment]
Current error on Jenkins server 
Could not find an executable 'phantomjs' that matched the requirements '>= 1.8.1', '< 3.0'. Found versions were {"/var/lib/jenkins/workspace/PR testing - CALS/node_modules/.bin/phantomjs"=>"294"}.

**Comment by lauherkcambria** [comment]
now that we removed awesome print and byebug and got errors fixed on jenkins, @ratneshraval @anuroop15 @lavanyareddyreddy , does this PR look good to merge?

**Comment by ratneshraval** [comment]
What's our plan to remove auth check in feature tests?

**Comment by lauherkcambria** [comment]
@ratneshraval  we found a fix by replacing that auth check with the following:

`allow_any_instance_of(CalsBaseController).to` receive(:authenticate_with_cwds).and_return(true)`
 
this will bring code . coverage down to 95%, but we aren't 100% sure about how to get around this so we will make a user story to research and bring coverage back up to 100.

**Comment by ratneshraval** [comment]
Ruby coverage dropped to 95%. We need to create a separate story and bring that up to 100%.
Otherwise it looks good.

**Pull request merged**
