### PR TITLE
Ruby version

### PR DESCRIPTION
**Pull request by ratneshraval**
#### Brief feature description
- Set a ruby version

#### Do any commands needs to be run in order to run the project with this PR?
- `rvm install 2.4.2`  if you don't have 2.4.2 installed

### CODE REVIEW

**Comment by Nasir2712** [comment]
@ratneshraval branch is failing

**Comment by ratneshraval** [comment]
retest this please.

**Comment by ratneshraval** [comment]
retest this please

**Comment by ratneshraval** [comment]
@Nasir2712 all green now.

**Pull request merged**
