### PR TITLE
fix ie11

### PR DESCRIPTION
**Pull request by lauherkcambria**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
- N/A

#### Which User story does this relate to?
- https://www.pivotaltracker.com/story/show/145470913

#### Brief feature description
- fix search not working in IE 11

#### Does this PR block/effect other stories?
- no

#### Do any commands needs to be run in order to run the project with this PR?
- no

#### Code coverage percent diff as a result of this PR?
- N/A

#### JS errors diff as a result of this PR?
- N/A

### CODE REVIEW

**Comment by ratneshraval** [comment]
Would replacing whatwg-fetch with -polyfill version fix it? And help us for such future issues of fetch?
Or do we need to add this new package.

**Comment by lauherkcambria** [comment]
this approach allows us to include the plugin in one place and work for all of our javascript modules. I think this approach is easiest and most efficient. My choice for including this plugin rather than a polyfill is that it would be less refactoring.

**Comment by lauherkcambria** [comment]
that said though, if you would like to explore other ways of fixing this bug by all means go for it! I think your question is more along the lines of, 'should we be really using whatwg-fetch instead of something better that doesn't break IE11?'

**Comment by lauherkcambria** [comment]
in which case, i believe that research should be it's own user story, and this bug should be approved in the meantime as a fix for our current setup.

**Comment by ratneshraval** [comment]
I say we go with this fix. If we run into another issue with fetch then we can create a spike. Otherwise just live with this fix.

**Comment by lauherkcambria** [comment]
sounds good to me 😆

**Pull request merged**
