### PR TITLE
CALS-5113 - Facility profile error - No FacilityID present

### PR DESCRIPTION
**Pull request by Nasir2712**
#### Which User story does this relate to?
- https://osi-cwds.atlassian.net/browse/CALS-5113

#### Brief feature description
- Handle facility Id null value.

#### Does this PR block/effect other stories?
- no

#### Do any commands needs to be run in order to run the project with this PR?
- n/a

#### Code coverage percent diff as a result of this PR?
-

### CODE REVIEW

**Comment by ratneshraval** [comment]
So you can use this as the story https://osi-cwds.atlassian.net/browse/CALS-5113.
I think ID needs to be used only for link/url, everywhere else you probably need to keep the license_number. We need to discuss tomorrow with PO/Business.

**Comment by Nasir2712** [comment]
So ID needs to get be replaced with license number because that is the only field that is common for both LIS and CWS/CMS. If you want to use license number then we need have to more checks to see the source first and based on it assign a value.

**Comment by Nasir2712** [comment]
@ratneshraval Ok updated.

**Comment by Nasir2712** [comment]
checkforNA actually works for every field. The only field that's different is this district name which sends a name and a number. If the backend can just convert that to id and value, we don't have to write any other methods.

**Comment by sunilb0575** [comment]
I agree, except full name, date and facility Id we can use checkForNA for all.

**Pull request merged**
