### PR TITLE
Rails subdir deploy

### PR DESCRIPTION
**Pull request by ratneshraval**
#### What tests were added (if relevant)?
- Yes

#### Which User story does this relate to?
- https://www.pivotaltracker.com/story/show/147236849
- https://www.pivotaltracker.com/story/show/147236777

#### Brief feature description
- Use environment variable RAILS_RELATIVE_URL_ROOT to adjust app when deployed in sub-directory. 

#### Does this PR block/effect other stories?
- Yes. Pre-int and all other state environment deploys. 

#### Do any commands needs to be run in order to run the project with this PR?
- 

#### Code coverage percent diff as a result of this PR?
- Ruby 100%, JS 77%

#### JS errors diff as a result of this PR?
- 0

### CODE REVIEW

**Comment by ratneshraval** [comment]
retest this please.

**Comment by ratneshraval** [comment]
Retest this please.

**Comment by ratneshraval** [comment]
Retest this please.

**Comment by ratneshraval** [comment]
@lauherkcambria @anuroop15 @lavanyareddyreddy Can you download this branch and run all tests on your machine? The tests are passing for me but Jenkins is getting stuck.

**Comment by ratneshraval** [comment]
The tests are passing when connected to Jenkins directly.

**Comment by anuroop15** [comment]
@ratneshraval : All tests are passing when I run this branch

**Comment by ratneshraval** [comment]
Jenkins, retest this please.

**Pull request merged**
