### PR TITLE
Relationship text bug cals 5478

### PR DESCRIPTION
**Pull request by lauherkcambria**
#### Which User story does this relate to?
-https://osi-cwds.atlassian.net/browse/CALS-5478

#### Brief feature description
- fix for multiple applicants and multiple children for text entry into the relationship freeform field.

#### Does this PR block/effect other stories?
- no

#### Do any commands needs to be run in order to run the project with this PR?
-no 

#### Code coverage percent diff as a result of this PR?
-no

### CODE REVIEW

**Comment by ratneshraval** [comment]
So there is no gap between repeating child cards, It is really hard to know where a card starts and where it ends. Please check design.

**Comment by lauherkcambria** [comment]
@ratneshraval that is per the original design. Regardless, It's not related to this bug and shouldn't hold up the approval of this PR, right?

**Comment by lauherkcambria** [comment]
image
@ratneshraval as per design

**Comment by lauherkcambria** [comment]
@ratneshraval agreed 👍

**Pull request merged**
