### PR TITLE
Facility search on address

### PR DESCRIPTION
**Pull request by lavanyareddyreddy**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
-no, yes

#### Which User story does this relate to?
-#145625217

#### Brief feature description
-ability to search on address of a facility

#### Does this PR block/effect other stories?
-no

#### Do any commands needs to be run in order to run the project with this PR?
- no

#### Code coverage percent diff as a result of this PR?
-100.0% covered at 6.68 hits/line

#### JS errors diff as a result of this PR?
-na

### CODE REVIEW

**Comment by anuroop15** [comment]
@lauherkcambria what kind of tests your taking about??

**Comment by lavanyareddyreddy** [comment]
@lauherkcambria my latest commit has tests for search. please check it out.

**Comment by ratneshraval** [comment]
1 test is failing for me. 
./spec/features/search_facility_spec.rb:9 # Search Search a facility

**Comment by ratneshraval** [comment]
This branch is from before the jenkins PR setup so the tests will not automatically pass.

**Pull request merged**
