### PR TITLE
Rfa directory structure

### PR DESCRIPTION
**Pull request by ratneshraval**
#### What tests were added (if relevant), and do all tests (rspec, karma, and integration CALS tests) pass?
- Yes all tests pass

#### Which User story does this relate to?
- Restructuring for index/list view story

#### Brief feature description
- 'forms' directory updated to reflect 'rfa_forms/rfa01a_edit'

#### Code coverage percent diff as a result of this PR?
- 54% JS

#### JS errors diff as a result of this PR?
- 86

### CODE REVIEW

**Comment by ratneshraval** [comment]
> i'm not really sure what this refactor gives us that we didn't have before -- as far as granularity is concerned, i don't know if the renaming to be 'edit' really makes sense as this UI isn't just for editing the form but also used for new/create. either way works for me though if this change makes more sense to everyone else then great lets go for it 👍 😄

Technically it is edit for existing application but we can rename it to something else which makes more sense. What would be your suggestion on the naming for that?

**Comment by lavanyareddyreddy** [comment]
codeclimate -> 70 issues to fix. are we ignoring them?

**Comment by ratneshraval** [comment]
> codeclimate -> 70 issues to fix. are we ignoring them?

They are all "similar code found" errors and we can add a refactor story to look at them later but safe to ignore now.

**Comment by lauherkcambria** [comment]
> Technically it is edit for existing application but we can rename it to something else which makes more sense. What would be your suggestion on the naming for that?

For me the way it was already named made sense to me and i don't really see the need for this change. But as I was saying before, if this makes more sense this way for the rest of the team, lets go for it. 😄

**Pull request merged**
