### PR TITLE
Fix vcr for integration

### PR DESCRIPTION
**Pull request by TylerOSI**
#### Which User story does this relate to (link)?
- No story, but it unblocks several stories

#### Brief feature description
- We need to run VCR against integration now since we don't have preint. This fixes the setup and tests to run, so that we can develop locally with VCR. I also disabled all the RFA application tests since that code is not in production.

#### Do any commands needs to be run in order to run the project with this PR?
- I don't think so.

### CODE REVIEW

**Comment by TylerOSI** [comment]
Jenkins test this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by TylerOSI** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by TylerOSI** [comment]
retest this please

**Comment by TylerOSI** [comment]
Jenkins test this please

**Pull request merged**
