### PR TITLE
AARA-331: use new RFA 1A PUT call which accept complete RFA 1A object

### PR DESCRIPTION
**Pull request by LeonidMarushevskyi**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/AARA-331

#### Brief feature description
- Replacing logic in rfa1a controller to use new RFA 1A PUT which accepts complete RFA 1A object. Now Rails layer will just proxy call to backend API instead of splitting of RFA to parts and making separate calls to granular APIs. This change is needed to resolve issues related to lack of transaction in partial calls to backend API.

#### Does this PR block/effect other stories?
-

#### Do any commands needs to be run in order to run the project with this PR?
-

#### Code coverage percent diff as a result of this PR?
-

### CODE REVIEW

**Comment by LeonidMarushevskyi** [comment]
@lauherkcambria Controller code returned back for potential future use. Regarding parameters wite listing, validation and security on Rails layer I would try an approach where Rails proxy request from React to Java Layer without any processing. Java API already provides type validation, business validation, and address security concerns.

**Comment by lauherkcambria** [comment]
jenkins retest this please

**Comment by LeonidMarushevskyi** [comment]
jenkins retest this please

**Comment by lauherkcambria** [comment]
jenkins retest this please

**Pull request merged**
