### PR TITLE
Rubocop remove guardclause rule

### PR DESCRIPTION
**Pull request by ratneshraval**
#### Brief feature description
- Disable guardclause from rubocop

### CODE REVIEW

**Comment by ratneshraval** [comment]
@sunilb0575  @Nasir2712  what do you guys think about disabling this check?

**Comment by Nasir2712** [comment]
I am ok with it. Keeping this on was creating readibility issues.

**Comment by sunilb0575** [comment]
It is more readable when we use the simple if else, so lets disable it.

**Comment by ratneshraval** [comment]
retest this please

**Pull request merged**
