### PR TITLE
AARA-234: values under "other_people_using_residence_as_mailing" persists 

### PR DESCRIPTION
**Pull request by anuroop15**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/AARA-234

#### Brief feature description
- Remove "other_people_using_residence_as_mailing" key from residence object when values under "others_using_residence_as_mailing" is selected as 'false' 

#### Does this PR block/effect other stories?
- NA

#### Do any commands needs to be run in order to run the project with this PR?
- NA

#### Code coverage percent diff as a result of this PR?
- improved branch coverage

### CODE REVIEW

**Comment by Nasir2712** [comment]
retest this please

**Comment by anuroop15** [comment]
jenkins retest this please

**Comment by LeonidMarushevskyi** [comment]
Agree with comment above that one method should clearly articulate that it sets up default values on condition change and another deletes data on condition change

**Comment by anuroop15** [comment]
@lauherkcambria And @LeonidMarushevskyi  updated handle method as per comments.

**Comment by LeonidMarushevskyi** [comment]
jenkins retest this please

**Pull request merged**
